const datasetsJS = {
  "Erroringgame": {
    "lost lace": 42,
    "karmelita": 20,
    "seth": 4,
    "nyleth": 5,
    "gurr the outcast": 4,
    "the unravelled": 2,
    "raging conchfly": 4,
    "groal": 3,
    "lace 2": 7,
    "grand mother silk": 2,
    "first sinner": 8,
    "phantom": 3,
    "great conchflies": 2,
    "skull tyrant": 2,
    "last judge": 13,
    "cogwork dancers": 4,
    "trobbio": 6,
    "moss mother 2": 2,
    "moss mother": 1,
    "bell beast": 3,
    "lace": 2,
    "fourth chorus": 2,
    "moorwing": 11,
    "sister splinter": 5,
    "widow": 2,
    "tormented trobbio": 4,
    "pinstress": 4,
    "craw father": 2,
    "forebrother signis": 2,
    "lugoli": 4,
    "palestag": 1,
    "second sentinel": 2
  },
  "Goombafire": {
    "moss mother": 1,
    "bell beast": 3,
    "lace": 1,
    "fourth chorus": 1,
    "moorwing": 8,
    "sister splinter": 3,
    "widow": 5,
    "savage beastfly": 2,
    "skull tyrant": 2,
    "moss mother 2": 2,
    "last judge": 5,
    "skull tyrant 2": 1,
    "cogwork dancers": 2,
    "savage beastfly 2": 6,
    "forebrother signis": 3,
    "great conchflies": 1,
    "the unravelled": 7,
    "raging conchfly": 4,
    "trobbio": 6,
    "groal": 6,
    "phantom": 1,
    "lugoli": 3,
    "first sinner": 7,
    "broodmother": 3,
    "lace 2": 5,
    "grand mother silk": 2,
    "shakra": 2,
    "second sentinel": 1,
    "bell eater": 1,
    "plasmified zango": 1,
    "pinstress": 1,
    "father of the flame": 2,
    "seth": 1,
    "nyleth": 5,
    "crust king khan": 1,
    "karmelita": 6,
    "tormented trobbio": 2,
    "lost lace": 21
  },
  "Jmar": {
    "moss mother": 1,
    "bell beast": 1,
    "fourth chorus": 5,
    "sister splinter": 4,
    "savage beastfly": 5,
    "skull tyrant": 2,
    "widow": 2,
    "moss mother 2": 1,
    "great conchflies": 2,
    "phantom": 7,
    "cogwork dancers": 9,
    "moorwing": 50,
    "trobbio": 5,
    "lace 2": 8,
    "grand mother silk": 5,
    "last judge": 2,
    "forebrother signis": 1,
    "second sentinel": 1,
    "broodmother": 1,
    "raging conchfly": 2,
    "shakra": 3,
    "the unravelled": 2,
    "bell eater": 9,
    "crust king khan": 1,
    "voltvyrm": 2,
    "seth": 4,
    "nyleth": 8,
    "karmelita": 15,
    "lost lace": 60,
    "tormented trobbio": 8,
    "gurr the outcast": 2,
    "craw father": 1,
    "palestag": 3,
    "clover dancers": 2,
    "plasmified zango": 2,
    "watcher at the edge": 1
  },
  "Speakers": {
    "moss mother": 1,
    "bell beast": 3,
    "lace": 2,
    "fourth chorus": 1,
    "moorwing": 21,
    "savage beastfly": 25,
    "sister splinter": 7,
    "widow": 9,
    "moss mother 2": 4,
    "great conchflies": 1,
    "skull tyrant": 1,
    "last judge": 13,
    "cogwork dancers": 2,
    "broodmother": 6,
    "forebrother signis": 8,
    "trobbio": 5,
    "phantom": 3,
    "second sentinel": 1,
    "lace 2": 8,
    "raging conchfly": 5,
    "savage beastfly 2": 10,
    "grand mother silk": 4,
    "lugoli": 3,
    "first sinner": 7,
    "shakra": 6,
    "bell eater": 7,
    "garmond": 5,
    "tormented trobbio": 14,
    "pinstress": 8,
    "karmelita": 15,
    "gurr the outcast": 3,
    "palestag": 2,
    "clover dancers": 7,
    "seth": 8,
    "nyleth": 9,
    "the unravelled": 4,
    "crust king khan": 1,
    "lost lace": 22,
    "voltvyrm": 1,
    "watcher at the edge": 2,
    "plasmified zango": 1
  },
  "Thatlegend101": {},
  "Yonobro": {}
};
const colorMapJS = {
  "bell beast": "#F26060",
  "bell eater": "#608BF2",
  "broodmother": "#B5F260",
  "clover dancers": "#F260E0",
  "cogwork dancers": "#60F2D9",
  "craw father": "#F2AF60",
  "crust king khan": "#8560F2",
  "father of the flame": "#67F260",
  "first sinner": "#F26091",
  "forebrother signis": "#60BBF2",
  "fourth chorus": "#E6F260",
  "garmond": "#D360F2",
  "grand mother silk": "#60F2A9",
  "great conchflies": "#F27E60",
  "groal": "#606DF2",
  "gurr the outcast": "#97F260",
  "karmelita": "#F260C2",
  "lace": "#60ECF2",
  "lace 2": "#F2CD60",
  "last judge": "#A360F2",
  "lost lace": "#60F278",
  "lugoli": "#F26073",
  "moorwing": "#609DF2",
  "moss mother": "#C8F260",
  "moss mother 2": "#F160F2",
  "nyleth": "#60F2C7",
  "palestag": "#F29C60",
  "phantom": "#7260F2",
  "pinstress": "#79F260",
  "plasmified zango": "#F260A4",
  "raging conchfly": "#60CEF2",
  "savage beastfly": "#F2EB60",
  "savage beastfly 2": "#C160F2",
  "second sentinel": "#60F296",
  "seth": "#F26C60",
  "shakra": "#607FF2",
  "sister splinter": "#AAF260",
  "skull tyrant": "#F260D4",
  "skull tyrant 2": "#60F2E5",
  "the unravelled": "#F2BB60",
  "tormented trobbio": "#9060F2",
  "trobbio": "#60F266",
  "voltvyrm": "#F26086",
  "watcher at the edge": "#60B0F2",
  "widow": "#DAF260"
};
